from customer import *
from branch import *
from base import ALFABaseModel
from CGI import *
from communication import *
from customer_tariff import *
from group import *
from lead_reject import *
from lead_source import *
from lead_status import *
from lesson import *
from location import *
from log import *
from pay import *
from regular_lesson import *
from room import *
from study_status import *
from subject import *
from tariff import *
from task import *
from teacher import *
